name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  greetings:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello There!'

test:
  name: Test
  runs-on: ubuntu-latest
  steps:
    # CLONE REPO
    - name: Checkout
      uses: actions/checkout@v2.4.0

    # INSTALL NODE
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17

    # INSTALL POSTGRESQL
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: 'my_db'
        postgresql user: 'test_user'
        postgresql password: 'test_password'
 # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm install

      # RUN TESTS
      - name: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm t
