name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  greetings:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello There!'

test:
  name: Test
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses:
